version: '3.9'
services:
  mongodb:
    image: mongo:7.0
    container_name: web-music-player-mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  app:
    build: .
    container_name: web-music-player-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017/musicdb
      - JWT_SECRET=super_secret_key
    volumes:
      - .:/app

volumes:
  mongo_data:
